---
- name: Run Hello World Docker container
  hosts: all
  become: true

  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: semihamurcu66/hello-world
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: hello-world
        image: semihamurcu66/hello-world
        state: started
        restart_policy: always
        ports:
          - "80:80"
