name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: semihamurcu66
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}


    - name: Build Docker image
      run: docker build -t semihamurcu66/hello-world:latest ./docker-hello

    - name: Push Docker image to Docker Hub
      run: docker push semihamurcu66/hello-world:latest
