name: Build & Deploy Docker Image

on:
  push:
    paths:
      - Dockerfile

jobs:
  build-deploy:
    runs-on: self-hosted  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t hello-hybrid .

      - name: Run container
        run: docker run hello-hybrid
