name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: semihamurcu66
        password: 8Df*UnuWp.Q5!TA

    - name: Build Docker image
      run: docker build -t semihamurcu/hello-world:latest .

    - name: Push Docker image to Docker Hub
      run: docker push semihamurcu/hello-world:latest
